#!/usr/bin/env node

process.env.FORCE_COLOR = true;

const program = require('commander');
const package = require('../package.json');

program
  .version(`${package.name}@${package.version}`)
  .command('lint', 'eslint following airbnb rules')
  .command('clean', 'cross-platform remove')
  .command('build', 'compile into npm (lib) and umd (dist) standards')
  .command('start', 'development server with hmr')
  .command('test', 'run tests')
  .parse(process.argv);
