#!/usr/bin/env node

process.env.FORCE_COLOR = true;

const program = require('commander');
const package = require('../package.json');

program
  .version(`${package.name}@${package.version}`)
  .command('init', 'create folders & files')
  .command('lint', 'eslint following airbnb rules')
  .command('clean', 'cross-platform remove')
  .command('bundle', 'create bundles with webpack')
  .command('start', 'development server with hmr')
  .command('test', 'run tests')
  .command('build', 'transpile es6 into es5 with babel (npm dependency usage)')
  .parse(process.argv);
