#!/usr/bin/env node

const program = require('commander');
const spawn = require('cross-spawn-async');
const chalk = require('chalk');
const path = require('path');
const paths = require('../default-paths');

const defaultPattern = [paths.lib, paths.dist];

program
  .option('-p, --pattern [file|dir|glob]*', 'clean a specific pattern')
  .parse(process.argv);

const cleanCmd = path.join(paths.bin, 'rimraf');
const pattern = program.pattern ? [program.pattern] : defaultPattern;
const cleanArgs = pattern;

process.stdout.write(chalk.gray('---cleaning---', '\n'));
process.stdout.write(chalk.blue('   rimraf', pattern.join(' '), '\n'));
var clean = spawn(cleanCmd, cleanArgs);

clean.stdout.on('data', data => process.stdout.write(data.toString()));
clean.stderr.on('data', data => process.stdout.write(chalk.red(data.toString(), '\n')));
clean.on('close', code => process.stdout.write(chalk.gray('---cleaning done---', '\n')));
