#!/usr/bin/env node

const program = require('commander');
const path = require('path');
const spawn = require('cross-spawn');
const chalk = require('chalk');

const SRC = 'src';
const LIB = 'lib';
const DIST = 'dist';

program.parse(process.argv);

const wcePath = path.dirname(__dirname);
const cleanCmd = path.join(wcePath, 'src/wce-clean');
const npmCmd = path.join(wcePath, 'src/build-npm');
const spawnOptions = { stdio: 'inherit' };

process.stdout.write(chalk.gray('---building---', '\n'));
spawn.sync(cleanCmd, spawnOptions);
spawn.sync(npmCmd, spawnOptions);
process.stdout.write(chalk.gray('---building done---', '\n'));

//build.stdout.on('data', data => process.stdout.write(data.toString()));
//build.stderr.on('data', data => process.stdout.write(chalk.red(data.toString(), '\n')));
//build.on('close', code => process.stdout.write(chalk.gray('---building done---', '\n')));
