#!/usr/bin/env node

const program = require('commander');
const path = require('path');
const spawn = require('cross-spawn-async');
const chalk = require('chalk');
const paths = require('../default-paths');

const SRC = 'src/**/*.js*';
const TEST = 'test/**/*.js*';
const defaultPattern = [SRC, TEST];

program
  .option('-p, --pattern [file|dir|glob]*', 'eslint a specific pattern')
  .parse(process.argv);

const wcePath = path.dirname(__dirname);
const configPath = path.join(wcePath, '.eslintrc');
const lintCmd = path.join(paths.bin, 'eslint');
const pattern = program.pattern ? [program.pattern] : defaultPattern;
const lintArgs = pattern.concat('--config', configPath, '--color');

process.stdout.write(chalk.yellow('---linting---', '\n'));
process.stdout.write(chalk.blue('eslint', pattern.join(' '), '\n'));
var lint = spawn(lintCmd, lintArgs);

lint.stdout.on('data', data => process.stdout.write(data.toString()));
lint.stderr.on('data', data => process.stdout.write(chalk.red(data.toString(), '\n')));
lint.on('close', code => process.stdout.write(chalk.yellow('---linting done---', '\n')));
