#!/usr/bin/env node

const program = require('commander');
const path = require('path');
const spawn = require('cross-spawn-async');
const chalk = require('chalk');
const paths = require('../default-paths');
const fs = require('fs');

const TEST = 'test/**/*.js*';
const defaultPattern = [TEST];

program
  .option('-p, --pattern [file|dir|glob]*', 'test a specific pattern')
  .parse(process.argv);

const wcePath = path.dirname(__dirname);
const mochaBabelHookPath = path.join(wcePath, 'mocha-babel-hook');
const nycCmd = path.join(wcePath, paths.bin, 'nyc');
const mochaCmd = path.join(wcePath, paths.bin, '_mocha');
const pattern = program.pattern ? [program.pattern] : defaultPattern;
const testArgs = [
  '--require', mochaBabelHookPath,
  '--recursive',
  '--check-leaks',
  '--reporter', 'text'
];

process.stdout.write(chalk.gray('---testing---', '\n'));
process.stdout.write(chalk.blue('   mocha', pattern.join(' '), '\n'));
try {
  fs.accessSync('test', fs.F_OK);

  var test = spawn(nycCmd, testArgs.concat([mochaCmd, pattern]));

  test.stdout.on('data', data => process.stdout.write(data.toString()));
  test.stderr.on('data', data => process.stdout.write(chalk.red(data.toString(), '\n')));
  test.on('close', code => process.stdout.write(chalk.gray('---testing done---', '\n')));
} catch (err) {
  process.stdout.write(chalk.red('   no test to run', '\n'));
  process.stdout.write(chalk.gray('---testing done---', '\n'));
}

