#!/usr/bin/env node

const program = require('commander');
const path = require('path');
const spawn = require('cross-spawn');
const chalk = require('chalk');

program
  .option('-t, --type <type>', 'build type (all (default), npm, umd)', /^all|umd|npm$/i, 'all')
  .parse(process.argv);

const wcePath = path.dirname(__dirname);
const cleanCmd = path.join(wcePath, 'src/wce-clean');
const npmCmd = path.join(wcePath, 'src/build-npm');
const umdCmd = path.join(wcePath, 'src/build-umd');
const spawnOptions = { stdio: 'inherit' };

process.stdout.write(chalk.gray('---building---', '\n'));
spawn.sync(cleanCmd, spawnOptions);
if (program.type === 'all' || program.type === 'npm') spawn.sync(npmCmd, spawnOptions);
if (program.type === 'all' || program.type === 'umd') spawn.sync(umdCmd, spawnOptions);
process.stdout.write(chalk.gray('---building done---', '\n'));
