#!/usr/bin/env node

const program = require('commander');
const spawn = require('cross-spawn-async');
const chalk = require('chalk');

const LIB = 'lib';
const DIST = 'dist';
const defaultPattern = [LIB, DIST];

program
  .option('-p, --pattern [file|dir|glob]*', 'clean a specific pattern')
  .parse(process.argv);

const cleanCmd = './node_modules/.bin/rimraf';
const pattern = program.pattern ? [program.pattern] : defaultPattern;
const cleanArgs = pattern;

process.stdout.write(chalk.gray('---cleaning---', '\n'));
process.stdout.write(chalk.blue('   rimraf', pattern.join(' '), '\n'));
var clean = spawn(cleanCmd, cleanArgs);

clean.stdout.on('data', data => process.stdout.write(data.toString()));
clean.stderr.on('data', data => process.stdout.write(chalk.red(data.toString(), '\n')));
clean.on('close', code => process.stdout.write(chalk.gray('---cleaning done---', '\n')));
